//! Shader format conversion via naga.
//!
//! WGSL is the universal source format (generated by the proc macro).
//! naga converts to whatever the driver needs:
//!   WGSL → SPIR-V (Vulkan)
//!   WGSL → MSL    (Metal — replaces our custom MSL emitter)
//!   WGSL → WGSL   (WebGPU — identity)
//!
//! This eliminates custom emitters. One source (WGSL), all targets via naga.

use alloc::format;
use alloc::string::String;
use alloc::vec::Vec;

#[cfg(feature = "naga-shaders")]
use naga::valid::{Capabilities, ValidationFlags, Validator};

/// Convert WGSL source to SPIR-V binary (for Vulkan).
#[cfg(feature = "naga-shaders")]
pub fn wgsl_to_spirv(wgsl: &str) -> Result<Vec<u32>, String> {
    let module = naga::front::wgsl::parse_str(wgsl).map_err(|e| format!("WGSL parse: {}", e))?;

    let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
    let info = validator
        .validate(&module)
        .map_err(|e| format!("WGSL validate: {}", e))?;

    let options = naga::back::spv::Options {
        lang_version: (1, 5),
        ..naga::back::spv::Options::default()
    };

    naga::back::spv::write_vec(&module, &info, &options, None)
        .map_err(|e| format!("SPIR-V emit: {}", e))
}

/// Convert WGSL source to MSL source string (for Metal).
/// Eliminates our custom MSL emitter — naga handles the translation.
#[cfg(feature = "naga-shaders")]
pub fn wgsl_to_msl(wgsl: &str) -> Result<String, String> {
    let module = naga::front::wgsl::parse_str(wgsl).map_err(|e| format!("WGSL parse: {}", e))?;

    let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
    let info = validator
        .validate(&module)
        .map_err(|e| format!("WGSL validate: {}", e))?;

    let options = naga::back::msl::Options {
        lang_version: (2, 4),
        ..naga::back::msl::Options::default()
    };

    let pipeline_options = naga::back::msl::PipelineOptions::default();

    let (msl_source, _) =
        naga::back::msl::write_string(&module, &info, &options, &pipeline_options)
            .map_err(|e| format!("MSL emit: {}", e))?;

    Ok(msl_source)
}

/// Convert SPIR-V binary to MSL source string.
#[cfg(feature = "naga-shaders")]
pub fn spirv_to_msl(spirv: &[u32]) -> Result<String, String> {
    let opts = naga::front::spv::Options::default();
    let module = naga::front::spv::parse_u8_slice(bytemuck_slice(spirv), &opts)
        .map_err(|e| format!("SPIR-V parse: {}", e))?;

    let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
    let info = validator
        .validate(&module)
        .map_err(|e| format!("validate: {}", e))?;

    let msl_opts = naga::back::msl::Options {
        lang_version: (2, 4),
        ..naga::back::msl::Options::default()
    };

    let pipeline_options = naga::back::msl::PipelineOptions::default();

    let (msl, _) = naga::back::msl::write_string(&module, &info, &msl_opts, &pipeline_options)
        .map_err(|e| format!("MSL emit: {}", e))?;

    Ok(msl)
}

/// Convert SPIR-V binary to WGSL source string.
#[cfg(feature = "naga-shaders")]
pub fn spirv_to_wgsl(spirv: &[u32]) -> Result<String, String> {
    let opts = naga::front::spv::Options::default();
    let module = naga::front::spv::parse_u8_slice(bytemuck_slice(spirv), &opts)
        .map_err(|e| format!("SPIR-V parse: {}", e))?;

    let mut validator = Validator::new(ValidationFlags::all(), Capabilities::all());
    let info = validator
        .validate(&module)
        .map_err(|e| format!("validate: {}", e))?;

    let flags = naga::back::wgsl::WriterFlags::empty();
    let wgsl = naga::back::wgsl::write_string(&module, &info, flags)
        .map_err(|e| format!("WGSL emit: {}", e))?;

    Ok(wgsl)
}

#[cfg(feature = "naga-shaders")]
fn bytemuck_slice(words: &[u32]) -> &[u8] {
    unsafe { core::slice::from_raw_parts(words.as_ptr() as *const u8, words.len() * 4) }
}
