//! WGSL → SPIR-V compilation via naga.
//!
//! Used by the Vulkan driver to convert WGSL shader source
//! (generated by the proc macro) into SPIR-V binary that
//! Vulkan can consume via vkCreateShaderModule.

#[cfg(feature = "vulkan")]
pub fn wgsl_to_spirv(wgsl_source: &str) -> Result<Vec<u32>, String> {
    // Parse WGSL
    let module = naga::front::wgsl::parse_str(wgsl_source)
        .map_err(|e| format!("WGSL parse error: {}", e))?;

    // Validate
    let mut validator = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    );
    let info = validator
        .validate(&module)
        .map_err(|e| format!("WGSL validation error: {}", e))?;

    // Emit SPIR-V
    let options = naga::back::spv::Options {
        lang_version: (1, 5), // SPIR-V 1.5
        ..naga::back::spv::Options::default()
    };
    let pipeline_options = naga::back::spv::PipelineOptions {
        shader_stage: naga::ShaderStage::Compute,
        entry_point: "main".to_string(), // naga may rename from the WGSL entry
    };

    let spv = naga::back::spv::write_vec(&module, &info, &options, Some(&pipeline_options))
        .map_err(|e| format!("SPIR-V emission error: {}", e))?;

    Ok(spv)
}
