//! Implementation of `#[derive(Vertex)]` — generates vertex layout metadata
//! from a struct's fields, mapping Rust types to GPU attribute formats.

use proc_macro2::TokenStream;
use quote::quote;
use syn::{Fields, ItemStruct, Type};

/// Generate the `Vertex` derive implementation for a struct.
///
/// Produces:
/// - `const ATTRIBUTES` — static array of `VertexAttribute`
/// - `fn vertex_layout()` — returns a `VertexLayout` with stride, step mode, and attributes
///
/// `VertexLayout.attributes` is `Vec<VertexAttribute>` (not const-compatible),
/// so we generate a function rather than a `const`.
pub(crate) fn expand_vertex_derive(input: &ItemStruct) -> Result<TokenStream, syn::Error> {
    let fields = match &input.fields {
        Fields::Named(named) => &named.named,
        _ => {
            return Err(syn::Error::new_spanned(
                input,
                "#[derive(Vertex)] only supports structs with named fields",
            ));
        }
    };

    // Verify #[repr(C)] is present
    let has_repr_c = input.attrs.iter().any(|a| {
        if a.path().is_ident("repr") {
            a.parse_args::<syn::Ident>()
                .map(|i| i == "C")
                .unwrap_or(false)
        } else {
            false
        }
    });

    if !has_repr_c {
        return Err(syn::Error::new_spanned(
            input,
            "#[derive(Vertex)] requires #[repr(C)] on the struct",
        ));
    }

    let struct_name = &input.ident;

    // Parse each field into an attribute descriptor
    let mut attr_entries = Vec::new();
    let mut offset: usize = 0;

    for (location, field) in (0u32..).zip(fields.iter()) {
        let field_name = field
            .ident
            .as_ref()
            .ok_or_else(|| syn::Error::new_spanned(field, "unnamed field"))?;

        let (format, size) = type_to_attribute_format(&field.ty).map_err(|msg| {
            syn::Error::new_spanned(&field.ty, format!("field `{}`: {}", field_name, msg))
        })?;

        let off = offset as u32;
        let loc = location;

        attr_entries.push(quote! {
            ::quanta::VertexAttribute {
                location: #loc,
                offset: #off,
                format: #format,
            }
        });

        offset += size;
    }

    let attr_count = attr_entries.len();

    Ok(quote! {
        impl #struct_name {
            /// Static attribute descriptors generated by `#[derive(Vertex)]`.
            pub const ATTRIBUTES: [::quanta::VertexAttribute; #attr_count] = [
                #(#attr_entries),*
            ];

            /// Build a `VertexLayout` for this vertex struct.
            ///
            /// Returns a layout with stride = `size_of::<Self>()`, per-vertex stepping,
            /// and attribute descriptors derived from the struct fields.
            pub fn vertex_layout() -> ::quanta::VertexLayout {
                ::quanta::VertexLayout {
                    stride: core::mem::size_of::<Self>() as u32,
                    step: ::quanta::StepMode::Vertex,
                    attributes: Self::ATTRIBUTES.to_vec(),
                }
            }
        }
    })
}

/// Map a Rust type to an `AttributeFormat` variant and its byte size.
///
/// Supported types:
/// - `f32` -> Float (4 bytes)
/// - `[f32; 2]` -> Float2 (8 bytes)
/// - `[f32; 3]` -> Float3 (12 bytes)
/// - `[f32; 4]` -> Float4 (16 bytes)
/// - `u32` -> UInt (4 bytes)
/// - `[u32; 2]` -> UInt2 (8 bytes)
/// - `[u32; 3]` -> UInt3 (12 bytes)
/// - `[u32; 4]` -> UInt4 (16 bytes)
/// - `i32` -> Int (4 bytes)
/// - `[i32; 2]` -> Int2 (8 bytes)
/// - `[i32; 3]` -> Int3 (12 bytes)
/// - `[i32; 4]` -> Int4 (16 bytes)
fn type_to_attribute_format(ty: &Type) -> Result<(TokenStream, usize), String> {
    match ty {
        Type::Path(path) => {
            let ident = path.path.segments.last().ok_or("empty type path")?;
            match ident.ident.to_string().as_str() {
                "f32" => Ok((quote! { ::quanta::AttributeFormat::Float }, 4)),
                "u32" => Ok((quote! { ::quanta::AttributeFormat::UInt }, 4)),
                "i32" => Ok((quote! { ::quanta::AttributeFormat::Int }, 4)),
                other => Err(format!(
                    "unsupported vertex attribute type `{}`. \
                     Supported: f32, u32, i32, [f32; 2..4], [u32; 2..4], [i32; 2..4]",
                    other
                )),
            }
        }
        Type::Array(arr) => {
            let elem_ident = match arr.elem.as_ref() {
                Type::Path(p) => p
                    .path
                    .segments
                    .last()
                    .map(|s| s.ident.to_string())
                    .ok_or("empty array element type")?,
                _ => return Err("unsupported array element type".into()),
            };

            let len = match &arr.len {
                syn::Expr::Lit(lit) => match &lit.lit {
                    syn::Lit::Int(int) => int
                        .base10_parse::<usize>()
                        .map_err(|e| format!("invalid array length: {}", e))?,
                    _ => return Err("array length must be an integer literal".into()),
                },
                _ => return Err("array length must be a literal".into()),
            };

            match (elem_ident.as_str(), len) {
                ("f32", 2) => Ok((quote! { ::quanta::AttributeFormat::Float2 }, 8)),
                ("f32", 3) => Ok((quote! { ::quanta::AttributeFormat::Float3 }, 12)),
                ("f32", 4) => Ok((quote! { ::quanta::AttributeFormat::Float4 }, 16)),
                ("u32", 2) => Ok((quote! { ::quanta::AttributeFormat::UInt2 }, 8)),
                ("u32", 3) => Ok((quote! { ::quanta::AttributeFormat::UInt3 }, 12)),
                ("u32", 4) => Ok((quote! { ::quanta::AttributeFormat::UInt4 }, 16)),
                ("i32", 2) => Ok((quote! { ::quanta::AttributeFormat::Int2 }, 8)),
                ("i32", 3) => Ok((quote! { ::quanta::AttributeFormat::Int3 }, 12)),
                ("i32", 4) => Ok((quote! { ::quanta::AttributeFormat::Int4 }, 16)),
                (elem, n) => Err(format!(
                    "unsupported vertex attribute type `[{}; {}]`. \
                     Supported lengths: 2, 3, 4 for f32/u32/i32",
                    elem, n
                )),
            }
        }
        _ => Err("unsupported vertex attribute type".into()),
    }
}
