//! Rustc-shell-out harness: turn a kernel's Rust source into a
//! `wasm32-unknown-unknown` binary.
//!
//! Given the raw `extern "C" fn` form of a kernel (the same shape
//! `wasm_twin::emit_wasm_twin` produces, but as a string), this
//! module:
//! 1. Wraps it in a self-contained `no_std` source file with a panic
//!    handler and inlined `quanta::intrinsics` extern decls. The
//!    wrapping is total — no external crate deps — so rustc can
//!    compile it standalone.
//! 2. Hashes the wrapped source for caching.
//! 3. If the cache already holds a compiled wasm for that hash,
//!    returns its bytes.
//! 4. Otherwise invokes `rustc` directly (NOT `cargo`, to avoid
//!    nested-build issues when this runs from inside a proc-macro)
//!    with `--target wasm32-unknown-unknown --crate-type=cdylib`,
//!    then caches and returns the result.
//!
//! Cache layout: `<target>/quanta-wasm-cache/<hex-hash>/kernel.wasm`.
//! `<target>` is `$CARGO_TARGET_DIR` when set (cargo sets it), else
//! `<workspace>/target` (derived from `CARGO_MANIFEST_DIR`).
//!
//! This is the cutover bridge for roadmap step 058 phase 3: with this
//! in place, `kernel_macro::expand_kernel` can stop calling
//! `parse::parse_kernel` and instead call into rustc → wasm-lowering
//! to produce a `KernelDef`. Slice 5b only ships the harness; the
//! switchover lives in slice 5d, which is when these symbols become
//! reachable from the macro entry points. The module-level `dead_code`
//! allow keeps the build clean until then.

#![allow(dead_code)]

use std::collections::hash_map::DefaultHasher;
use std::ffi::OsString;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::process::Command;

/// Inlined copy of `src/intrinsics.rs`. We take the file verbatim and
/// strip its leading `#![cfg(target_arch = "wasm32")]` line at use
/// site — that attribute makes the module empty when included from a
/// non-wasm crate. The wrapper we emit is *already* a wasm32 crate so
/// the gate is redundant.
const INTRINSICS_SRC: &str = include_str!("../../../src/intrinsics.rs");

/// Compile a kernel's `extern "C" fn` source to a `wasm32-unknown-
/// unknown` binary. Returns the wasm bytes on success.
///
/// `kernel_decl` must be the complete `pub unsafe extern "C" fn` item
/// (including `#[unsafe(no_mangle)]`). It can call any function from
/// `quanta::intrinsics` — those decls are inlined into the wrapper at
/// `mod quanta { pub mod intrinsics { ... } }` so `use
/// quanta::intrinsics::*;` works inside the kernel body.
pub(crate) fn compile_kernel_to_wasm(kernel_decl: &str) -> Result<Vec<u8>, String> {
    let wrapped = wrap_kernel_source(kernel_decl);
    let hash = hash_source(&wrapped);
    let cache_dir = cache_dir_for(&hash)?;
    let wasm_path = cache_dir.join("kernel.wasm");

    if wasm_path.is_file() {
        return fs::read(&wasm_path)
            .map_err(|e| format!("read cached wasm at {}: {e}", wasm_path.display()));
    }

    fs::create_dir_all(&cache_dir)
        .map_err(|e| format!("create cache dir {}: {e}", cache_dir.display()))?;
    let src_path = cache_dir.join("lib.rs");
    fs::write(&src_path, &wrapped).map_err(|e| format!("write {}: {e}", src_path.display()))?;

    invoke_rustc(&src_path, &wasm_path)?;

    fs::read(&wasm_path).map_err(|e| format!("read built wasm at {}: {e}", wasm_path.display()))
}

/// Wrap a kernel decl in a self-contained no_std crate with the
/// intrinsic externs in scope as `quanta::intrinsics::*`.
fn wrap_kernel_source(kernel_decl: &str) -> String {
    let intrinsics = strip_intrinsics_top_attrs(INTRINSICS_SRC);
    format!(
        "//! Auto-generated by quanta-macros::wasm_compile — do not edit.\n\
         #![no_std]\n\
         #![allow(unused, dead_code, unused_unsafe)]\n\
         \n\
         #[panic_handler]\n\
         fn _quanta_panic(_: &core::panic::PanicInfo) -> ! {{ loop {{}} }}\n\
         \n\
         pub mod quanta {{\n\
             pub mod intrinsics {{\n\
                 {intrinsics}\n\
             }}\n\
         }}\n\
         \n\
         {kernel_decl}\n",
    )
}

/// Strip the file-level `#![cfg(target_arch = "wasm32")]` and
/// `#![allow(...)]` attributes from the inlined `intrinsics.rs` —
/// they're inner attributes that only make sense when the file is the
/// crate root or a module's own file. When we splice the body into a
/// nested `mod intrinsics { ... }` they're rejected.
fn strip_intrinsics_top_attrs(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    for line in src.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("#![") {
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn hash_source(src: &str) -> String {
    let mut hasher = DefaultHasher::new();
    src.hash(&mut hasher);
    format!("{:016x}", hasher.finish())
}

fn cache_dir_for(hash: &str) -> Result<PathBuf, String> {
    let target = target_dir()?;
    Ok(target.join("quanta-wasm-cache").join(hash))
}

/// Resolve the target directory. Prefers `$CARGO_TARGET_DIR`; falls
/// back to `<CARGO_MANIFEST_DIR>/target`. CARGO_MANIFEST_DIR is set
/// by cargo whenever it invokes a proc-macro build.
fn target_dir() -> Result<PathBuf, String> {
    if let Some(dir) = std::env::var_os("CARGO_TARGET_DIR")
        && !dir.is_empty()
    {
        return Ok(PathBuf::from(dir));
    }
    let manifest = std::env::var_os("CARGO_MANIFEST_DIR")
        .ok_or_else(|| "neither CARGO_TARGET_DIR nor CARGO_MANIFEST_DIR is set".to_string())?;
    Ok(PathBuf::from(manifest).join("target"))
}

fn invoke_rustc(src_path: &Path, wasm_out: &Path) -> Result<(), String> {
    let rustc: OsString = std::env::var_os("RUSTC").unwrap_or_else(|| OsString::from("rustc"));
    let out = Command::new(&rustc)
        .arg("--target")
        .arg("wasm32-unknown-unknown")
        .arg("--crate-type=cdylib")
        .arg("--edition=2024")
        .arg("-C")
        .arg("opt-level=3")
        .arg("-C")
        .arg("panic=abort")
        .arg("-C")
        .arg("strip=debuginfo")
        .arg("-o")
        .arg(wasm_out)
        .arg(src_path)
        .output()
        .map_err(|e| {
            format!(
                "spawn rustc ({}): {e} — install the wasm32-unknown-unknown target with `rustup target add wasm32-unknown-unknown`",
                rustc.to_string_lossy()
            )
        })?;
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr);
        return Err(format!(
            "rustc failed compiling kernel to wasm32:\n{stderr}\n(source written to {})",
            src_path.display()
        ));
    }
    Ok(())
}

/// Heuristic: is the wasm32 target installed and rustc reachable?
/// Used by tests to skip cleanly on machines where it isn't.
#[cfg(test)]
pub(crate) fn wasm32_target_available() -> bool {
    let rustc: OsString = std::env::var_os("RUSTC").unwrap_or_else(|| OsString::from("rustc"));
    let Ok(out) = Command::new(&rustc)
        .args(["--print", "target-list"])
        .output()
    else {
        return false;
    };
    if !out.status.success() {
        return false;
    }
    let list = String::from_utf8_lossy(&out.stdout);
    if !list.lines().any(|l| l.trim() == "wasm32-unknown-unknown") {
        return false;
    }
    // Target is *known* to rustc; check that its sysroot has the std
    // surface for it (i.e. the user ran `rustup target add`).
    let probe = Command::new(&rustc)
        .args(["--target", "wasm32-unknown-unknown", "--print", "sysroot"])
        .output();
    matches!(probe, Ok(o) if o.status.success())
}

#[cfg(test)]
mod tests {
    use super::*;

    const VECTOR_ADD_DECL: &str = r#"
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn vector_add(
            a: *const f32,
            b: *const f32,
            result: *mut f32,
        ) {
            #[allow(unused_imports)]
            use crate::quanta::intrinsics::*;
            unsafe {
                let i = quark_id() as usize;
                *result.add(i) = *a.add(i) + *b.add(i);
            }
        }
    "#;

    #[test]
    fn round_trip_compiles_and_caches() {
        if !wasm32_target_available() {
            eprintln!(
                "[wasm_compile] skipping: wasm32-unknown-unknown target not installed \
                 (rustup target add wasm32-unknown-unknown)"
            );
            return;
        }

        let bytes_a =
            compile_kernel_to_wasm(VECTOR_ADD_DECL).expect("first compile should succeed");
        assert!(
            bytes_a.starts_with(b"\0asm"),
            "output should be a WASM binary (magic bytes \\0asm)"
        );

        let bytes_b = compile_kernel_to_wasm(VECTOR_ADD_DECL)
            .expect("second compile should hit cache and succeed");
        assert_eq!(
            bytes_a, bytes_b,
            "second call must return identical bytes (cache hit)"
        );
    }

    #[test]
    fn different_sources_get_different_hashes() {
        let a = wrap_kernel_source("pub extern \"C\" fn k() {}");
        let b = wrap_kernel_source("pub extern \"C\" fn k2() {}");
        assert_ne!(hash_source(&a), hash_source(&b));
    }

    #[test]
    fn intrinsic_top_attrs_stripped() {
        let stripped = strip_intrinsics_top_attrs(INTRINSICS_SRC);
        assert!(
            !stripped.contains("#![cfg(target_arch"),
            "wasm32 cfg gate must be stripped from inlined intrinsics"
        );
        assert!(
            stripped.contains("pub fn quark_id"),
            "extern decls must survive stripping"
        );
    }
}
